name: Android Build CI

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "assets/**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Haxe
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3

      # Cache Haxelib
      - name: Cache Haxelib
        uses: actions/cache@v3
        with:
          path: |
            $HAXELIB_ROOT
          key: ${{ runner.os }}-haxelib-${{ hashFiles('haxelib.json') }}

      # Setup Android SDK & JDK
      - uses: android-actions/setup-android@v2
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r15c

      # Install Haxelib dependencies
      - name: Setup Haxelib packages
        run: |
          mkdir -p "$HAXELIB_ROOT"
          haxelib setup "$HAXELIB_ROOT"
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install hxcpp --quiet
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install hscript --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib git polymod https://github.com/MasterEric/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-webm https://github.com/jigsaw-4277821/extension-webm --quiet
          haxelib git linc_luajit https://github.com/Daninnocent/linc_luajit.git --quiet
          haxelib install actuate --quiet
          haxelib list

      # Build Android APK
      - name: Build APK
        run: |
          haxelib run lime setup android
          haxelib run lime build android -Dci -release

      # Upload APK artifact (v4)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: export/release/android/bin/app/build/outputs/apk/release/app-release.apk          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install hscript --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib git polymod https://github.com/MasterEric/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-webm https://github.com/jigsaw-4277821/extension-webm --quiet
          haxelib git linc_luajit https://github.com/Daninnocent/linc_luajit.git --quiet
          haxelib install actuate --quiet
          haxelib list

      # Build Android APK
      - name: Build APK
        run: |
          haxelib run lime setup android
          haxelib run lime build android -Dci -release

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Android-APK
          path: export/release/android/bin/app/build/outputs/apk/release/app-release.apk
